from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BankTransactionViewSet, webhook_receiver, transaction_list

# Create a router for handling viewsets
router = DefaultRouter()
router.register(r'transactions', BankTransactionViewSet, basename='transaction')

# Define the URL patterns
urlpatterns = [
    # Include the URLs generated by the router for the 'transactions' viewset
    path('api/', include(router.urls)),
    # Define a URL for the webhook_receiver view with the name 'webhook_receiver'
    path('api/webhook_receiver/', webhook_receiver, name='webhook_receiver'),
    # Define a URL for the transaction_list view with the name 'transaction_list'
    path('transactions/', transaction_list, name='transaction_list'),  
]
